services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes: {}